name: CI/CD

on:
  push:
    branches:
      - develop

jobs:
  load-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v1

      - name: Instalar dependências do k6
        run: npm install -g k6

      - name: Executar testes de carga
        run: k6 run --summary-export=summary.json script.js

  send_email:
    needs: load-testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v2

      - name: Baixar o resumo dos testes
        uses: actions/download-artifact@v2
        with:
          name: summary
          path: summary.json

      - name: Gerar relatório HTML
        run: k6 report -o performance-inteligente.html summary.json

      - name: Enviando o email com o report
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          KEY_GENERATE: ${{ secrets.KEY_GENERATE }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
          ARTIFACT_PATH: ./performance-inteligente.html
        run: |
          node ./email-sender/send-email.js ${{ env.ARTIFACT_PATH }}
