name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job_1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
   
      - name: run Load testing in K6.io
        uses: k6io/action@v0.1
        with:
          filename: script.js
      
     
      - name: Upload html report for job 1
        uses: actions/upload-artifact@v2
        with:
          name: performance
          path: performance-inteligente.html
          retention-days: 2
    
  
